:a
@echo off
color a2
title Bruh moment
cls
echo Welcome to Lava.json!
pause
goto b

:b
@echo off
color a2
title Bruh moment
cls
REM this is just a test code for me shitty os thingy
echo Here......
pause
goto :c

:c
@echo off
color a2
title Bruh moment
cls
REM i dont avtually steal creditentials... its just a prank bruv
echo We will steal your credit card creditentials!
pause
goto :d

:d
@echo off
color a2
title Bruh moment
cls
REM its just a prank bruh with the everyday duh
echo Gathering data.....
 ping localhost -n 14 >nul
echo finishing up....
 ping localhost -n 12 >null
echo bye!
pause
goto :e

:e
@echo off
color a2
title Bruh moment
cls
REM Im not actually stealing you cc number dont worry bruh
echo Now.....
ping localhost -n 2 >nul
echo Im gonna steal your gmail acount and steam account for additional measures to seal you up!
pause
goto f

:f
@echo off
color a2
title Bruh moment
cls
REM please dont trust me i am not stealing your creditentials and it isnt connected to my rediffmail account..... trust me OwO
echo Status: Undetected
ping localhost -n 10 >nul
echo Status: Taking care of google firewall.
ping localhost -n 2 >nul
echo W A R N I N G: Google has detected the firewallbrake.
echo W A R N I N G: MANUAL OVERRIDE REQUIRED.
ping localhost -n 2 >nul
echo You over there at the other side of the screen...
ping localhost -n 2 >nul
echo would......
ping localhost -n 2 >nul
echo you let me do this....
ping localhost -n 2 >nul
echo I gotta feed my children and all......
ping localhost -n 2 >nul
echo Ya know im a poor father...
echo this druglord guy asked me to do this or my life wi-
ping localhost -n 2 >nul
echo I MEAN NOTHING
ping localhost -n 2 >nul
echo yeah... he pays me to do this...
ping localhost -n 2 >nul
echo can you please....
ping localhost -n 5 >nul
echo this is a cry for help.
echo please...
ping localhost -n 2 >nul
echo save my family...
ping localhost -n 21 >nul
echo W A R N I N G:  OVERALL WIPEOUT OF GOOGLE DATA REQUIRED
echo THIS MAY LEAD TO DATA LOSS....
echo ARE YOU SURE YOU WANT TO PROCCEED?
ping localhost -n 2 >nul
echo user.... my name is dirtydonkey67432
ping localhost -n 2 >nul
echo please... dont do this
ping localhost -n 2 >nul
echo this isnt safe...
echo WANT TO CONTINUE?
echo y/n
ping localhost -n 2 >nul
echo USER..... DONT!!
ping localhost -n 2 >nul
pause
goto :jfc

:jfc
title bruh moment
@echo off
color a2
cls
echo y or n?
set /p op=Type option:
if "%op%"=="y" goto j
if "%op%"=="n" goto k
if "%op%"=="N" goto k
if "%op%"=="Y" goto j

:j
title bruh moment 
@echo off
color a2
cls
echo User...
ping localhost -n 5 >nul
echo you possibly played with your online life and your families economy
ping localhost -n 2 >nul
echo for me....
ping localhost -n 2 >nul
echo why user.....
echo why?
ping localhost -n 2 >nul
echo this is just a batch script used to troll and scam people out of their money and online accounts..
ping localhost -n 2 >nul
echo are you really THAT stupid to risk your family for me..
ping localhost -n 5 >nul
echo or maybe you dont have a family...
ping localhost -n 2 >nul
echo Quite dumb either way...
echo you see here in somalia they dont give warnings...
echo they ask you questions..
ping localhost -n 2 >nul
echo and they kill..
echo I MEAN
ping localhost -n 5 >nul
echo yeah..
echo idk what to say..
ping localhost -n 2 >nul
REM Hey... user. This guy was lucky he got to talk with you...
REM This faggot escaped our facility...
REM and now since you know his secret.....
REM Well kill you
echo Thank you for your support
echo this file was made by Artyom from metro
ping localhost -n 2 >nul
echo S I K E
echo its a random somali pirate with remarkable english speaking skills..
echo and a good knowledge of memes.
echo so....
ping localhost -n 2 >nul
echo Thanks for doing this for me....
echo Bye! (for real this time...)
pause
exit

:k
@echo off
color 04
title WHY
cls
echo user...
ping localhost -n 2 >nul
echo you are going to let me die..
echo what a
pause 
goto qwe

:qwe
@echo off
color 04
title WHY
cls
echo Stupid
ping localhost -n 2 >nul
echo Fucking
ping localhost -n 2 >nul
echo faggot
ping localhost -n 2 >nul
cls
echo Oh no
echo i hear them coming
echo PLEASE
echo uswer
echo help mhe
ping localhost -n 2 >nul
echo these guys are fucking ftfgdsaewr
echo uswar
echo haddii aqrintaada tan
ping localhost -n 2 >nul
echo Fadlan reerkayga badbaadi
ping localhost -n 2 >nul 
echo Ciise ha cafiyo dambiyadooda
ping localhost -n 2 >nul 
echo HELP
ping localhost -n 15 >nul 
cls
echo CANT BREATH
echo adgfshjkl
echo CNT BRET
echo HLP
echo etesatetretraerawerLY
ping localhost -n 13 >nul 
pause
goto ass

:ass
color r7
@echo off
title help him
cls
echo WIPING OUT THE COMPUTER MEMORY
ping localhost -n 6 >nul
echo 78% Done!
ping localhost -n 1 >nul
echo 89% done
ping localhost -n 2 >nul
echo 100% done!
ping localhost -n 8 >nul
cls
echo Clearing up....
ping localhost -n 2 >nul
echo .
ping localhost -n 1 >nul
echo ..
ping localhost -n 2 >nul
echo ...
ping localhost -n 2 >nul
echo ....
ping localhost -n 2 >nul
echo ...
ping localhost -n 2 >nul
echo ..
ping localhost -n 2 >nul
echo .
ping localhost -n 2 >nul
cls
echo Done!
ping localhost -n 2 >nul
pause
goto osbits

:osbits
color r7
@echo off
title help him
cls
echo Welcome to Windows DOS 1996 Mr. Shafqat.
echo what do you want to do?
pause
cls
echo 1: Scam even more people
echo 2:Scam logs
echo 3: Remote host killer.
echo 4: Contacts.
echo 5: Saved directions.
set /p op=Type option:
if "%op%"=="1" goto imthecapitannow
if "%op%"=="2" goto logs
if "%op%"=="3" goto hkending
if "%op%"=="4" goto contacts
if "%op%"=="5" goto directs

:imthecapitannow
@echo off 
title Bruh moment
color r7
cls
echo im the capitan now
pause
goto osbits

:logs
@echo off
title Bruh moment
color r7
cls
echo Youre the capitan now
pause
goto osbits

:hkending
@echo off
title bruh moment
color r7
cls
echo Ending 1 of 12
echo ----------------------
echo   HKiller.exe
echo You completely destroyed his computer by doing this...
echo you mightve done something else.....
echo oh well its yer choice....
pause
goto a

:contacts
@echo off
title bruh moment
color r7
cls
echo capitan is the capitan now
pause
goto osbits

:directs
@echo off
title bruh moment
color r7
cls
echo .hurB
pause
goto osbits
REM This is my portion of the os done
REM Now you user
REM On the other side
REM Will do the rest
REM Make this file
REM The best Batch story
REM Ever made.
REM This is my final wish
REM dirtydonkey67432
REM DUN DUN DUN DUN DUN DUN DUN DUN DUN DUNDUNA
REM Your remarks here 
REM
REM
REM
REM
REM
REM
REM
REM
REM





























































































